# Generated by Django 5.1.7 on 2025-03-31 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT Company'), ('Finance', 'Finance Company'), ('Healthcare', 'Healthcare Company'), ('Education', 'Education Institute'), ('Other', 'Other')], max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('Manager', 'Manager'), ('Software Developer', 'SD'), ('Project leader', 'PL')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
