# Generated by Django 5.1.7 on 2025-03-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT Company'), ('Finance', 'Finance Company'), ('Healthcare', 'Healthcare Company'), ('Education', 'Education Institute'), ('Other', 'Other')], max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
